<?xml version="1.0" encoding="utf-8"?><Database Name="FabioDB" Class="LinqToSQLDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-LPL69IA\FABIOSQL;Initial Catalog=FabioDB;Persist Security Info=True;User ID=sa" SettingsObjectName="LinqToSQL.Properties.Settings" SettingsPropertyName="FabioDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.University" Member="University">
    <Type Name="University">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>